server:
  port: 9090

spring:
  application:
    name: TaskForge DAG Scheduler
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.taskforge: DEBUG
    org.springframework.web: INFO
    